const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const P=require('../dist/air-support-policy.js');
const a={T:{eng:4,str:10,ammo:400,guns:2,fuel:250,cls:'f'},engHp:4,strHp:10,ctlHp:3,dmg:0,fuel:250,ammo:[400,400]};
assert.deepEqual(P.service(a),{repair:0,cost:0,seconds:24});
const damaged={...a,engHp:2,strHp:5,ctlHp:1,dmg:.4,ammo:[160,160],fuel:100};
const q=P.service(damaged);assert.ok(q.cost>q.repair&&q.repair>50&&q.seconds>60);
assert.ok(P.service({...damaged,engHp:1}).cost>q.cost);
assert.ok(P.replacement(a.T)>q.cost);
assert.equal(P.clear([{x:100,y:100,tx:300,ty:100}],280,100,100),false,'planned advance is protected');
const state={time:100,team:0,width:2400,front:1200,y:1000,phase:'prepare',next:{cap:200,rec:200},flights:[],own:Array.from({length:20},()=>({x:500,y:1000,tx:600,ty:1000})),contacts:Array.from({length:10},(_,i)=>({id:i,x:1550+i,y:1000,hp:100,at:98,type:'rifle'}))};
assert.equal(P.choose(state).kind,'bmb');
assert.equal(P.choose({...state,contacts:state.contacts.map(e=>({...e,at:70}))}),null,'stale contacts cannot authorize bombing');
assert.equal(P.choose({...state,grounded:true}),null);
assert.equal(P.choose({...state,preparing:true}),null);
assert.equal(P.choose({...state,own:state.own.slice(0,8)}),null,'recover infantry first');
assert.equal(P.choose({...state,intruder:{x:800,y:1000}}).kind,'int');
const ctx=vm.createContext({console,performance});ctx.window=ctx;ctx.location={search:''};ctx.PX={Z:.5};ctx.IronFront={};ctx.IronFrontAirPolicy=P;ctx.PXFORT={isPrep:()=>false};ctx.IronFrontBrain={lastPlans:[null,null]};
vm.runInContext(`const W=2400,H=2000;let units=[],buildings=[],bullets=[],shells=[],planes=[],particles=[],time=0,started=true,ended=false,playerTeam=0,sandbox=false,cam={x:1200,y:1000},supplies=[0,0],aiEnabled=[false,false],placement=null,keys={};const defs={};function setup(){}function update(dt){time+=dt}function place(){}function makeCards(){}function incomeFor(){return 12}function toast(){}function sound(){}function hud(){}`,ctx);
for(const f of ['airwar.js','battle-air-command.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),ctx,{filename:f});
const run=s=>vm.runInContext(s,ctx);run('setup();var plane=PXAW.planes().find(a=>a.team===0);plane.st="taxiin";plane.path=[];plane.pi=0;plane.engHp=2;plane.dmg=.3;update(.05)');
assert.ok(run('plane.serviceWaiting&&plane.ready===Infinity&&plane.engHp===2'),'no free repair on arrival');
run('supplies[0]=1000;var quote=IronFrontAirCommand.waiting()[0];IronFrontAirCommand.update(.1);var cash=supplies[0]');
assert.equal(run('1000-supplies[0]'),run('quote.cost'));assert.equal(run('plane.ready-time'),run('quote.seconds'));
run('IronFrontAirCommand.update(.1)');assert.equal(run('supplies[0]'),run('cash'),'no double charge');
run('var slots=PXAW.airfields()[1].slots;var lost=slots[0];lost.ac.dead=true;lost.lostAt=0;time=120;supplies[1]=0;PXAW._internals.step(.05)');
assert.ok(run('lost.ac.dead'),'no free replacement');
run('supplies[1]=1000;for(let i=0;i<65;i++){time+=.05;PXAW._internals.step(.05)}');assert.ok(run('!lost.ac.dead'));assert.equal(run('IronFrontAirCommand.state().replacements[1]'),1);
run('time=0;setup();time=20;supplies=[1000,1000];var before=supplies[0];var flight=IronFrontAirCommand.request(0,"cap",1000,1000,{manual:true,n:2});');
assert.equal(run('before-supplies[0]'),90);assert.equal(run('flight.m.length'),2);
run('time+=3;IronFrontAirCommand.update(.1)');assert.ok(run('IronFrontAirCommand.events().some(e=>e.kind==="resposta")'));
console.log('Air command: observed targets, friendly routes, weather, troop reserve, paid service/replacement, real orders and acknowledgments OK');
