const assert=require('node:assert/strict'),S=require('../dist/battle-stories.js'),O=require('../dist/battle-opportunities.js'),M=require('../dist/squad-mind.js');
const unit=(id,x=700,y=480)=>({id,team:0,type:'rifle',hp:100,maxhp:100,x,y,suppression:0,manualUntil:0,cohesion:1});
const members=[unit(1),unit(2),unit(3),unit(4)];
const source={id:1,kind:'infantry',task:'avanço-alternado'};
let state={team:0,time:0,units:members,points:[],height:2000,visibilityRange:350,trenches:[]};
M.update(source,members,state);
const group={id:1,ids:members.map(u=>u.id),kind:'infantry',source,members,x:700,y:480,pressure:0};
let orders=members.map(u=>({id:u.id,role:source.task})),mem=S.create();
assert.deepEqual(S.update(mem,state,[group],orders),[]);
source.task='flanco-apoiado';orders=members.map(u=>({id:u.id,role:source.task}));state.time=5;
let e=S.update(mem,state,[group],orders);assert.equal(e.length,2);assert.equal(e[1].kind,'resposta');assert.ok(e[1].time>e[0].time);
assert.equal(e[0].speaker,source.mind.leader);assert.match(e[0].text,/cobertura|MG/);
source.task='retirada-coberta';state.time=6;e=S.update(mem,state,[group],members.map(u=>({id:u.id,role:source.task})));assert.equal(e.length,2,'limite global impede conversa em todo comando');
state.time=35;source.task='ocupar-trincheira';orders=members.map(u=>({id:u.id,role:source.task}));members[1].manualUntil=50;state.controlledId=3;
e=S.update(mem,state,[group],orders);assert.equal(e.length,2);assert.equal(e[1].speaker,4,'resposta respeita ordem humana e soldado controlado');
state.time=60;state.controlledId=1;source.task='consolidação';assert.equal(S.update(mem,state,[group],orders).length,0,'controlado não fala pela IA');
state.controlledId=null;source.task='avanço-alternado';state.time=70;M.update(source,members,state);state.time=75;members[3].hp=0;M.update(source,members.slice(0,3),state);assert.equal(source.mind.losses,1);assert.equal(source.mind.scars.length,1);
state.time=80;M.update(source,members.slice(0,3),state);assert.equal(source.mind.losses,1,'perdas não se repetem');
const fresh=S.create();source.mind.lastStoryAt=-100;state.time=0;state.points=[{name:'A',x:700,y:480,owner:1}];S.update(fresh,state,[group],orders);state.points[0].owner=0;state.time=30;
e=S.update(fresh,state,[group],orders);assert.equal(e[0].kind,'conquista');assert.equal(source.mind.victories,1);
assert.equal(S.update(S.create(),state,[group],[]).length,0,'sem ordens executadas, não inventa diálogo');
source.occupation=null;source.task='avanço-alternado';state.time=100;state.trenches=[{id:'enemy',x:820,y:480,hp:100,team:1,line:'front'}];
let choice=O.choose(group,state,[],'avanço-alternado',{x:1100,y:480});assert.equal(choice.task,'ocupar-trincheira');
state.time=110;choice=O.choose(group,state,[],'avanço-alternado',{x:1100,y:480});assert.equal(choice.task,'ocupar-trincheira');
state.time=130;choice=O.choose(group,state,[],'avanço-alternado',{x:1100,y:480});assert.equal(choice.task,'avanço-alternado','prazo impede ocupação interminável');
state.time=160;state.clearSight=()=>false;assert.equal(O.choose(group,state,[],'avanço-alternado',{x:1100,y:480}).task,'avanço-alternado','trincheira não observada não vira alvo');
state.clearSight=()=>true;state.shells=[{x:820,y:480,r:70,t:2}];assert.equal(O.choose(group,state,[],'avanço-alternado',{x:1100,y:480}).task,'avanço-alternado','ocupação evita impacto iminente');
function g(id,x,y,reserve){const m=Array.from({length:4},(_,i)=>unit(id*10+i,x,y));return {id,kind:'infantry',x,y,members:m,pressure:0,source:{reserve,mind:{recoverUntil:0}}}}
const groups=[g(1,900,480,false),g(2,1000,800,false),g(3,850,650,true),g(4,700,1000,true)];
state={...state,time:20,shells:[],clearSight:()=>true};const op={phase:'advance',since:0,sector:{id:1,front:720,y:480}};
const sectors=[{id:1,x:930,y:480,target:{},threat:5},{id:2,x:1100,y:800,target:{},threat:1,score:8}];
assert.ok(O.reserve(groups,state,[],op,sectors,false));assert.equal(groups.filter(g=>g.source.exploit).length,1,'só uma reserva se compromete');
assert.equal(O.reserve(groups.slice(0,3),state,[],{...op,phase:'hold'},sectors,false),null);
assert.equal(O.reserve(groups.slice(0,3),{...state,time:60},[],op,sectors,false),null,'conserva a última reserva');
// Personalities produce different real destinations under the same local threat.
const team=Array.from({length:4},(_,i)=>unit(100+i));team[0].hp=25;team.forEach(u=>u.suppression=.6);
const tactical={...state,time:160,units:team,trenches:[{team:0,hp:100,x:680,y:480}],shells:[]};
const local={kind:'infantry',x:700,y:480,members:team},enemy=[{id:90,type:'rifle',x:800,y:480,at:160}];
const protective={id:3,mind:{profile:'protetor',morale:.5,recoverUntil:0}};
assert.equal(M.maneuver(protective,local,tactical,'avanço-alternado',{x:930,y:480},enemy,false,720).task,'retirada-coberta');
const cautious={id:1,mind:{profile:'prudente',morale:.8,recoverUntil:0}};
assert.equal(M.maneuver(cautious,local,tactical,'avanço-alternado',{x:930,y:480},enemy,false,720).goal.x,680);
const bold={id:2,mind:{profile:'impetuoso',morale:.8,recoverUntil:0}};
assert.equal(M.maneuver(bold,local,tactical,'avanço-alternado',{x:930,y:480},enemy,false,720).goal.x,930);
console.log('Battle stories: diálogos reais, respostas, limites, ordens humanas, memória, ocupação observada e reserva limitada OK');
