const assert=require('node:assert/strict'),S=require('../dist/squad-mind.js');
const unit=(id,extra={})=>({id,team:0,type:'rifle',hp:100,maxhp:100,x:700,y:480,suppression:0,cohesion:1,manualUntil:0,...extra});
const source={id:1,kind:'infantry',task:'avanço-alternado'},state={team:0,time:0,controlledId:1,trenches:[]};
let members=[unit(1),unit(2),unit(3),unit(4)];let m=S.update(source,members,state);assert.equal(m.leader,2,'controlado não recebe ordens de liderança da IA');
state.time=5;members=members.filter(u=>u.id!==2);m=S.update(source,members,state);assert.equal(m.leader,null);assert.ok(m.replaceAt>5);
state.time=10;m=S.update(source,members,state);assert.equal(m.leader,3,'liderança tem substituição limitada');
const before=m.morale;state.time=40;members[1].hp=20;members[1].suppression=1.8;members[2].hp=20;members[2].suppression=1.8;
m=S.update(source,members,state);assert.ok(m.morale<before);assert.equal(m.state,'reorganizando');
const move=S.maneuver(source,{kind:'infantry',members,x:700,y:480},state,'avanço-alternado',{x:930,y:480},[],false,720);assert.equal(move.task,'reorganização-local');
for(const u of members){u.suppression=0;u.underFire=0}source.task='reserva-movel';for(const time of [60,80,100,120]){state.time=time;m=S.update(source,members,state)}assert.ok(m.morale>.5);assert.notEqual(m.state,'reorganizando');
const target={x:900,y:480};S.intent(source,'avanço-alternado',target,state,'avançar');const held=S.intent(source,'avanço-alternado',{x:910,y:480},state,'avançar');assert.equal(held.goal.x,900,'destino estável evita jitter');
const manual=unit(20,{manualUntil:130});assert.equal(S.apply(manual,{tx:900,ty:480,role:'assalto'},120,null),false);assert.equal(manual.aiRole,undefined);
const controlled=unit(1);assert.equal(S.apply(controlled,{tx:900,ty:480,role:'assalto'},120,1),false);
const evasive=unit(21,{dodgeUntil:122});assert.equal(S.apply(evasive,{tx:900,ty:480,role:'assalto'},120,null),false);
const free=unit(22);assert.equal(S.apply(free,{tx:900,ty:480,role:'assalto',reason:'teste'},120,null),true);assert.equal(free.aiIntent.owner,'esquadrao');
const tactical={id:2,mind:{recoverUntil:0}},g={kind:'infantry',x:700,y:480,members};state.time=120;
assert.equal(S.maneuver(tactical,g,state,'avanço-alternado',target,[{id:90,type:'mg',x:850,y:480,at:120}],true,720).task,'fixar-flanquear');
assert.equal(S.maneuver(tactical,g,state,'avanço-alternado',target,[{id:90,type:'mg',x:850,y:480,at:120}],false,720).task,'avanço-alternado','flanco exige apoio real');
const scout={...g,kind:'scout',members:[unit(30)]};assert.equal(S.maneuver(tactical,scout,state,'reconhecimento',target,Array.from({length:3},(_,id)=>({id,x:800,y:480,at:120})),false,720).task,'patrulha-retornando');
console.log('Squad mind: liderança, substituição, moral, recuperação, ordens humanas, evasão, destinos estáveis, apoio e patrulhas OK');
