const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
process.env.NODE_PATH='C:/Users/ryan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';require('node:module').Module._initPaths();
const {chromium}=require('playwright'),root=path.resolve(__dirname,'../dist'),out=path.resolve(__dirname,'../tests/artifacts');
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!p.startsWith(root+path.sep)){res.writeHead(403);return res.end()}fs.readFile(p,(e,d)=>{if(e){res.writeHead(404);return res.end()}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(d)})});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),report={maps:[],errors:[]};
try{const page=await browser.newPage({viewport:{width:1360,height:900}});page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error'&&!/net::ERR|fonts.googleapis/.test(m.text()))report.errors.push(m.text())});await page.goto(`http://127.0.0.1:${server.address().port}/?preparo=5`);await page.locator('[data-go="sandbox"]').click();await page.locator('#start').click();
for(const map of ['trenches','forest','winter']){const result=await page.evaluate(map=>{document.getElementById('mapselect').value=map;document.getElementById('gametype').value='sandbox';document.getElementById('blueai').value='on';document.getElementById('redai').value='on';setup();running=false;PXFORT.endPrep();IronFrontBrain.setRoles(['attack','defend']);runCommander(0);runCommander(1);hud();render();minimap();return {map,points:IronFront.state().points,targets:IronFrontBrain.lastPlans.map(p=>p.sectors.map(s=>s.x)),guards:IronFrontBrain.lastPlans.map(p=>p.orders.filter(o=>o.role==='guarda-objetivo').map(o=>({x:o.tx,y:o.ty}))),labels:document.getElementById('objectives').textContent}} ,map);
assert.equal(result.points.length,2);assert.ok(result.points[0].x<350&&result.points[1].x>2050);assert.ok(result.points.every(p=>p.home===p.owner));assert.ok(result.guards.every(g=>g.length>0));report.maps.push(result);console.log(JSON.stringify(result));}
report.clock=await page.evaluate(()=>{aiEnabled=[false,false];sandbox=false;units=[];tickets=[500,500];for(let i=0;i<100;i++)update(.1);return {tickets:[...tickets],ended}});assert.deepEqual(report.clock.tickets,[500,500]);assert.equal(report.clock.ended,false);
for(const team of [0,1]){const result=await page.evaluate(team=>{setup();running=false;PXFORT.endPrep();sandbox=false;aiEnabled=[false,false];units=[];const p=points.find(p=>p.home===1-team);for(let i=0;i<8;i++){const u=newUnit('rifle',team,p.x,p.y);u.cls=undefined;u.sap=0;u.rs=null;u.manualUntil=0}for(let i=0;i<950&&!ended;i++)update(.1);hud();return {team,ended,owner:p.owner,title:document.getElementById('resulttitle').textContent}},team);assert.ok(result.ended);assert.equal(result.owner,team);report['capture'+team]=result;}
await page.evaluate(()=>{document.getElementById('result').close();setup();running=false;PXFORT.endPrep();cam.x=points[0].x+100;cam.y=points[0].y;hud();render();minimap()});assert.ok(await page.locator('.objective').evaluateAll(els=>els.every(el=>el.scrollWidth<=el.clientWidth)));await page.screenshot({path:path.join(out,'base-flag-rear.png')});
await page.goto(`http://127.0.0.1:${server.address().port}/?mapa=classico&preparo=5`);report.classic=await page.evaluate(()=>({height:H,points:IronFrontBases.create(W,H)}));assert.ok(report.classic.points.every(p=>p.y===800));assert.deepEqual(report.errors,[]);fs.writeFileSync(path.join(out,'base-objectives-report.json'),JSON.stringify(report,null,2));console.log('Base flags: three maps, both victories, guards, no initial ticket drain and classic map verified');
}finally{await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
